project_id = "wfyvnzcnhmrsheivbgip"

[auth]
enabled = true
site_url = "https://user-scan-hub.lovable.app"

[db]
schema = "public"

[functions.cleanup-ended-parties]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.send-guest-message]
verify_jwt = false