// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = "https://wfyvnzcnhmrsheivbgip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmeXZuemNuaG1yc2hlaXZiZ2lwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNTgzNzYsImV4cCI6MjA2OTgzNDM3Nn0.TWRzHl2wWCF71iRRHzNOdjwPR6e7i9G8ZkjUrdzqnIk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});